warehouse/force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

warehouse/force-app/main/default/objects/Customer__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

warehouse/force-app/main/default/objects/Customer__c/fields/Notify_By__c.field-meta.xml
<CustomField>
    <fullName>Notify_By__c</fullName>
    <label>Notify By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SMS</fullName>
                <default>true</default>
                <label>SMS</label>
            </value>
            <value>
                <fullName>EMail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

warehouse/force-app/main/default/objects/Customer__c/fields/SMS_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>SMS_Phone_Number__c</fullName>
    <label>SMS Phone Number</label>
    <type>Phone</type>
</CustomField>

warehouse/force-app/main/default/objects/Customer__c/fields/Twilio_From_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Twilio_From_Phone_Number__c</fullName>
    <label>Twilio From Phone Number</label>
    <type>Phone</type>
</CustomField>

warehouse/force-app/main/default/classes/CustomerNotificationAction.cls
public with sharing class CustomerNotificationAction {
	@InvocableMethod(label='Notification to a customer' description='Notify a customer with customer name by SMS or email based on their preference')
	public static void notifyCustomers(List<CustomerNotification> customerNotifications) {
		System.debug('Invocable action called: ' + customerNotifications.size());
		setCustomers(customerNotifications);

		for (CustomerNotification customerNotification: customerNotifications) {
			notifyCustomer(customerNotification);
		}
	}

	private static void notifyCustomer(CustomerNotification customerNotification) {
		if (customerNotification.customer != null) {
			List<Customer__c> customers = new List<Customer__c>();
			customers.add(customerNotification.customer);

			CustomerProductNotification notification = new CustomerProductNotification();
			notification.notify(customers, customerNotification.subject,
					unescapeFormulaBrs(customerNotification.message),
					unescapeFormulaBrs(customerNotification.shortMessage));
		}
	}

	private static void setCustomers(List<CustomerNotification> customerNotifications) {
		List<String> customerNames = new List<String>();
		Map<String, CustomerNotification> nameToCustomerNotifications = new Map<String, CustomerNotification>();
		for (CustomerNotification customerNotification: customerNotifications) {
			customerNames.add(customerNotification.customerName);
			nameToCustomerNotifications.put(customerNotification.customerName, customerNotification);
		}

		List<Customer__c> customers = [SELECT Name__c, Notify_By__c, SMS_Phone_Number__c, Twilio_From_Phone_Number__c
				FROM Customer__c
				WHERE Name__c IN :customerNames];

		for (Customer__c customer: customers) {
			CustomerNotification customerNotification = nameToCustomerNotifications.get(customer.Name__c);
			if (customerNotification != null) {
				customerNotification.customer = customer;
			}
		}
	}

	// Swap formula BR() _BR_ENCODED_ with \n
	// See knowlege article: https://success.salesforce.com/issues_view?id=a1p300000008YkZAAU
	private static String unescapeFormulaBrs(String formulaText) {
		return formulaText == null ? null : formulaText.replace('_BR_ENCODED_', '\n');
	}

	public class CustomerNotification {
		@InvocableVariable(required=true)
		public String customerName;

		public Customer__c customer;

		@InvocableVariable(required=true)
		public String subject;

		@InvocableVariable
		public String message;

		@InvocableVariable
		public String shortMessage;
	}
}