warehouse/force-app/main/default/objects/Products__x/Products__x.object-meta.xml
<CustomObject>
    <description>Products</description>
    <externalDataSource>Warehouse</externalDataSource>
    <externalName>Products</externalName>
    <label>Product</label>
    <pluralLabel>Products</pluralLabel>
</CustomObject>

warehouse/force-app/main/default/objects/Products__x/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Category</description>
    <externalDeveloperName>Category</externalDeveloperName>
    <label>Category</label>
    <length>128</length>
    <referenceTo>ProductCategories__x</referenceTo>
    <relationshipLabel>ProductCategories</relationshipLabel>
    <relationshipName>ProductCategories</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

warehouse/force-app/main/default/objects/Products__x/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <description>ProductId</description>
    <externalDeveloperName>ProductId</externalDeveloperName>
    <label>ProductId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

warehouse/force-app/main/default/objects/Products__x/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <description>UnitPrice</description>
    <externalDeveloperName>UnitPrice</externalDeveloperName>
    <label>UnitPrice</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

warehouse/force-app/main/default/classes/FlashSaleJob.cls
public with sharing class FlashSaleJob implements Database.Batchable<sObject> {
    private final String  category;
    private final Decimal priceAdjustment;
    private final Integer minPrice;
    private final Integer maxPrice;
    
    private Integer updatedRecordCount = 0;
    
    public FlashSaleJob(String category, Integer saleInPercent, 
                        Integer minPrice, Integer maxPrice) {
        this.category = category;
        this.priceAdjustment = 1.0 - (saleInPercent / 100.0);
        this.minPrice = minPrice;
        this.maxPrice = maxPrice;
    }
    
    public Database.QueryLocator start(Database.BatchableContext ctx) {
        if (!canAccessProducts()) {
            System.debug('Can\'t access Products__x');
        }
        String soql = 'SELECT ProductId__c, UnitPrice__c FROM Products__x ' +
            'WHERE Category__c = \'' + this.category + '\' AND ' +
            'UnitPrice__c >= ' + this.minPrice + ' AND ' +
            'UnitPrice__c <= ' + this.maxPrice + 
            ' ORDER BY ProductId__c';
        return Database.getQueryLocator(soql);
    }
    
    public void execute(Database.BatchableContext ctx, List<sObject> scope) {
        for (sObject p : scope) {
            Decimal originalPrice = (Decimal)p.get('UnitPrice__c');
            Decimal salePrice = originalPrice * this.priceAdjustment;
            p.put('UnitPrice__c', salePrice);
        }
        Database.updateAsync(scope); 
        updatedRecordCount += scope.size();           
    }
    
    public void finish(Database.BatchableContext ctx) {
        // Here we could send a notification, or write a log message.
        System.debug('Flash sale has been kicked off. Number of products with reduced price: ' 
            + updatedRecordCount);
    }

    private boolean canAccessProducts() {
        return Schema.SObjectType.Products__x.fields.ProductId__c.isAccessible();
    }
}